### ISSUE TITLE
forge password for puppet-downloadfile

### ISSUE THREAD

**Issue by liamjbennett** [puppet-community/plumbing#6]

**Comment by nibalizer** [comment]
Done. Is there overlap between puppet-download_file and nanliu/archive?

**Comment by liamjbennett** [comment]
Thanks. Yes almost certainly there is some overlap there. The only reason I am moving it here is that it is a highly downloaded module and a dependency on a couple of other OT modules to come. 

The overlap in modules that download files is something that I am aware of and once all our modules are in the community this might be something we want to discuss deprecating, but for now I think it should remain.
